package LeetCode;

/**
 *
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * <p>
 * Return the letter that was added to t.
 * <p>
 * Example 1:
 * <p>
 * Input: s = "abcd", t = "abcde"
 * <p>
 * Output: "e" Explanation: 'e' is the letter that was added.
 * <p>
 * Example 2:
 * <p>
 * Input: s = "", t = "y" Output: "y"
 *
 */
public class FindStrDifference {

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        char c = findTheDifference(s, t);
        System.out.println(c);
    }

    public static char findTheDifference(String s, String t) {
        char c = 0;
        for (char cs : s.toCharArray()) {
            c ^= cs;
        }
        for (char ct : t.toCharArray()) {
            c ^= ct;
        }

        return c;
    }
}
