server:
  port: 8082

spring:
  application:
    name: kafka-backend
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ecommerce-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all